server:
  port: 8080

spring:
  application:
    name: api-gateway
  config:
    import: optional:configserver:http://localhost:8888
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/users/**
          filters:
            - name: CircuitBreaker
              args:
                name: userServiceCb
                fallbackUri: forward:/fallback/users
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
resilience4j:
  circuitbreaker:
    instances:
      userServiceCb:
        slidingWindowSize: 20
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
