spring:
  application:
    name: user-service
  config:
    import: optional:configserver:http://localhost:8888
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      auto-offset-reset: earliest
      properties:
        spring.json.trusted.packages: "*"
    producer:
      properties:
        spring.json.add.type.headers: false
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
app:
  kafka:
    topics:
      user-events: user.events